accounts:
  - name: alice
    coins: ["200000000astrum"]
  - name: bob
    coins: ["100000000astrum"]
validator:
  name: alice
  staked: "100000000astrum"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["1000000000astrum"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "astrum"
    mint:
      params:
        mint_denom: "astrum"
    gov:
      deposit_params:
        min_deposit:
          amount: "10000000"
          denom: "astrum"